package app.eeh.bank.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import app.eeh.bank.db.table.BankCard;
import app.eeh.bank.db.table.User;

import app.eeh.bank.db.BankCardDao;
import app.eeh.bank.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bankCardDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BankCardDao bankCardDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bankCardDaoConfig = daoConfigMap.get(BankCardDao.class).clone();
        bankCardDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        bankCardDao = new BankCardDao(bankCardDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(BankCard.class, bankCardDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        bankCardDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public BankCardDao getBankCardDao() {
        return bankCardDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
